#################################################  
# Bryan R. Balajadia - 23 November 2015  
# Problem 2: Even Fibonacci numbers
################################################# 

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


My Solution

Fib <- c()
Fib[1] <- 1
Fib[2] <- 2
i <- 3

repeat {
  Fib[i] <- Fib[i-1] + Fib[i-2]
  if (Fib[i] > 4000000) break
  i <- i + 1
}

Fib <- Fib[-length(Fib)]   # remove the last term
result <- sum(Fib[Fib %% 2 == 0]) # calculate the sum of even numbers
result
# [1] 4613732
